# Generated by Django 4.1 on 2022-08-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20220809_2056'),
        ('polls', '0002_number'),
    ]

    operations = [
    ]
